version: "3.8"

services:

  mongodb:
    image: mongo:8.2
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: on-failure:100

  api:
    build: .
    entrypoint: bun watch-debug
    working_dir: /app
    volumes:
      - "./src:/app/src"
      - "./package.json:/app/package.json"
      - "./server.ts:/app/server.ts"
      - "./bun.lockb:/app/bun.lockb"
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: always
    environment:
      PORT: 3000
      DB: mongodb
