version: "3.2"

services:

  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    restart: always

  api:
    build: .
    command: npm run watch-debug
    working_dir: /app
    volumes:
      - "./src:/app/src"
      # - ./data:/tetris-api/db
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: always
    environment:
      PORT: 3000
      DB: mongodb
